version: '3'
services:
  db:
    image: postgres
    environment:
     POSTGRES_PASSWORD: embarcas
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/embarca-s
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
    environment:
      - RUBYOPT=-W0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - /usr/share/elasticsearch/data
    environment:
      - node.name=node-1
      - cluster.initial_master_nodes=node-1
